#! /bin/bash
echo -e "Content-type: text/html\r\n\r\n"
echo -e "<html><head><title>INFORMATION ON UNPROCESSED TAG FILES</title></head><body><pre>"
USER=`echo "$QUERY_STRING" | sed -n 's/^.*USER=\([^&]*\).*$/\1/p' | sed "s/%20/ /g"`
ORG=`echo "$QUERY_STRING" | sed -n 's/^.*ORG=\([^&]*\).*$/\1/p' | sed "s/%20/ /g"`
PASS=`echo "$QUERY_STRING" | sed -n 's/^.*PASS=\([^&]*\).*$/\1/p' | sed "s/%20/ /g"`

TSD_Check.py -u $USER -o $ORG -p $PASS --LS | TEE | TCC_Touch -u $USER -o $ORG -p $PASS - &
disown
